### ISSUE TITLE
Error calculating IOU

### ISSUE THREAD

**Issue by LDHGItU** [czq142857/BAE-NET#2]
Hi:
   When I train in an unsupervised way, the training phase is normal, but I encounter an error when I test the IOU, which prompts "imseg object has no attribute test" and how to solve this problem
Thanks

**Comment by czq142857** [comment]
We only provided code for testing IOUs on one-shot training results, since in that case, we know exactly which branch will output which part. For unsupervised training, the testing is a bit different because we cannot know which branch will output which part until after training is completed.

You need to visualize the segmentation results for a few shapes, and then manually assign a semantic label to the corresponding branch of the network. Once you have labeled all the branches of the network, you can easily modify function "test_pcSeg" to get the IOUs.

Best,
Zhiqin
