### ISSUE TITLE
Other scores of ShapeNet unsupervised

### ISSUE THREAD

**Issue by MrMois** [czq142857/BAE-NET#9]
Hello,

I really enjoyed your work, in particular the unsupervised segmentation part! Do you have the IOU score available for the unsupervised ShapeNet chair (back, seat, leg, arm) category, when it is trained without the table joint dataset?

Thanks in advance for your answer.

Greetings!

**Comment by czq142857** [comment]
Hi,

We have reported the numbers on chairs (unsupervised) in the paper, with three parts. We did not even compute the numbers for four parts because the network just outputted three parts. If you need the number, you can train the network with the provided code and data. The github repo contains both the oneshot version and the unsupervised version.

Best,
Zhiqin
